- hosts: localhost
  vars:
    ssh_private_personal_src: "./.ssh/id_ed25519"
    ssh_private_dst: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    asdf_bin: "/opt/asdf-vm/bin/asdf"
    asdf_sh: "/opt/asdf-vm/asdf.sh"
  pre_tasks:
  - name: Update Pacman
    become: true
    community.general.pacman:
      force: yes
      update_cache: true
      upgrade: true
      state: present
    tags:
      - base
  tasks:
    - include: tasks/ssh.yaml
    - include: tasks/packages.yaml
    - include: tasks/packages-work.yaml
    - include: tasks/zsh-setup.yaml
    - include: tasks/dotfiles.yaml
    - include: tasks/dotfiles-personal.yaml
    - include: tasks/languages.yaml
    - include: tasks/misc.yaml
