- hosts: localhost
  vars:
    ssh_private_key_src: "./.ssh/id_rsa"
    ssh_private_key_dst: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update Pacman
    become: true
    community.general.pacman:
      force: yes
      update_cache: true
      upgrade: true
      state: present
    tags:
      - base
  tasks:
    - include: tasks/ssh.yaml
