- name: Clone personal dotfiles
  git:
    repo: "git@github.com:mister11/.dotfiles-personal.git"
    dest: "~/.dotfiles-personal"
    accept_hostkey: true
  tags:
    - base
    - dotfiles-personal

- name: Symlink home personal stuff
  shell: |
    cd ~/.dotfiles-personal
    ./install home
  tags:
    - home
    - dotfiles-personal-home

- name: Symlink work personal stuff
  shell: |
    cd ~/.dotfiles-personal
    ./install work
  tags:
    - work
    - dotfiles-personal-work
