- name: Clone dotfiles
  git:
    repo: "git@github.com:mister11/.dotfiles.git"
    dest: "~/.dotfiles"
    accept_hostkey: true
  tags:
    - base
    - dotfiles
  
- name: Remove default zshrc (created by zsh install)
  shell: |
    if [ ! -L "$HOME/.zshrc" ] && [ -e "$HOME/.zshrc" ]; then
      rm $HOME/.zshrc
    fi
  tags:
    - base
    - dotfiles

- name: Stow dotfiles
  shell: |
    cd ~/.dotfiles
    ./install
  tags:
    - base
    - dotfiles
