- name: Install latest LTS Java version
  shell: |
    {{ asdf_bin }} plugin add java
    
    version=$({{ asdf_bin }} list all java | grep temurin-17 | tail -n 1)

    {{ asdf_bin }} install java $version
    {{ asdf_bin }} global java $version:
  tags:
    - base
    - languages
    - java

- name: Check if Rust installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"
  register: rust_installed
  tags:
    - base
    - languages
    - rust

- name: Install Rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  when: rust_installed.stat.exists == False
  tags:
    - base
    - languages
    - rust

- name: Update Rust
  shell: rustup update
  when: rust_installed.stat.exists == True
  tags:
    - base
    - languages
    - rust

- name: Install Erlang
  shell: |
    {{ asdf_bin }} plugin add erlang

    latest_version=$({{ asdf_bin }} list all erlang | grep -v "rc" | tail -n 1)

    {{ asdf_bin }} install erlang $latest_version
    {{ asdf_bin }} global erlang $latest_version
  tags:
    - base
    - languages
    - erlang

- name: Install Elixir
  shell: |
    {{ asdf_bin }} plugin add elixir

    source {{ asdf_sh }} && . ~/.local/bin/install_elixir
  tags:
    - base
    - languages
    - elixir

- name: Install Node
  shell: |
    {{ asdf_bin }} plugin add nodejs

    latest_version=$({{ asdf_bin }} list all nodejs | grep -v "[a-zA-Z]" | tail -n 1)

    source {{ asdf_sh }} && {{ asdf_bin }} install nodejs $latest_version
    {{ asdf_bin }} global nodejs $latest_version
  tags:
    - base
    - languages
    - node
