- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh_private_key_dst | dirname }}"
    mode: 0700
    state: directory
  tags:
    - base
    - ssh
- name: Install SSH private key
  copy:
    src: "{{ ssh_private_key_src }}"
    dest: "{{ ssh_private_key_dst }}"
    mode: 0600
  tags:
    - base
    - ssh
- name: Install SSH public key
  copy:
    src: "{{ ssh_private_key_src }}.pub"
    dest: "{{ ssh_private_key_dst }}.pub"
    mode: 0644
  tags:
    - base
    - ssh
