- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - base
    - zsh

- name: Check if Oh-My-ZSH is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh" 
  register: oh_my_zsh_exists
  tags:
    - base
    - zsh

- name: Install Oh-My-ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_zsh_exists.stat.exists == False
  tags:
    - base
    - zsh

- name: Install Oh-My-ZSH auto-complete plugin
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - base
    - zsh

- name: Install Oh-My-ZSH syntax highlighting plugin
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - base
    - zsh
